### ISSUE TITLE
feat: 是否会做Discord的相关功能

### ISSUE THREAD

**Issue by Walkersifolia** [armoe-project/armoe-plugin#10]
就是和现有KOOK类似，绑定以及查询

**Comment by RealHeart** [comment]
近期可能会开发

**Comment by RealHeart** [comment]
Discord 的 Widget JSON API 没有监听语言频道内容 做不了 或者有什么接口可以监测告知

**Comment by Walkersifolia** [comment]
> Discord 的 Widget JSON API 没有监听语言频道内容 做不了 或者有什么接口可以监测告知

好的，我去看看去
