### ISSUE TITLE
feat: 支持角色别名查询

### ISSUE THREAD

**Issue by AshenAshes** [armoe-project/armoe-plugin#3]
查主角攻略的时候发#开拓者攻略，#火主攻略 都没有反应
要发#开拓者·毁灭攻略 才行
请问是否考虑下支持角色别名的查询，可以参考这个大佬的别名文件https://github.com/Nwflower/Atlas/blob/master/resource/Forlibrary/star-rail-atlas/othername/role.yaml

**Comment by RealHeart** [comment]
可以 晚上看看
