### ISSUE TITLE
bug: Bot.getGroupMemberInfo is not a function

### ISSUE THREAD

**Issue by strike94** [armoe-project/armoe-plugin#6]
![image](https://user-images.githubusercontent.com/34638547/236715678-75af4e00-dc65-4b91-a290-0ecb86276d7e.png)
r6s查询使用时提示Bot.getGroupMemberInfo is not a function

**Comment by RealHeart** [comment]
请提供环境信息
我在Yunzai-Bot和Miao-Yunzai均正常使用

**Comment by strike94** [comment]
使用的TRSS-Yunzai，系统Debian11.2，使用TRSS-Script一键安装，根据Github中TRSS-Yunzai的解释，是基于Miao-Yunzai的

**Comment by RealHeart** [comment]
尝试使用最新提交，查看是否正常使用

**Comment by strike94** [comment]
![image](https://user-images.githubusercontent.com/34638547/236851929-0f35a59f-dc37-48cd-9a81-04f546a0faa1.png)
还是无法正常使用

**Comment by RealHeart** [comment]
> ![image](https://user-images.githubusercontent.com/34638547/236851929-0f35a59f-dc37-48cd-9a81-04f546a0faa1.png) 还是无法正常使用

现在应该正常了

**Comment by strike94** [comment]
可以正常使用了，谢谢大佬
