### ISSUE TITLE
bug: 更新后无法正常查询r6战绩

### ISSUE THREAD

**Issue by BJY666** [armoe-project/armoe-plugin#7]
如图
![P6 Y KZ@)BQBPS%)W0RTE](https://github.com/armoe-project/armoe-plugin/assets/51154133/c58fcb8f-b93d-4b3f-8fc6-f3215b61da33)
![AG AMN9D0N6N3AZ@1_AL0UM](https://github.com/armoe-project/armoe-plugin/assets/51154133/070cd1ad-1124-4370-9a49-2712f0e867e0)

**Comment by RealHeart** [comment]
请提供环境信息

**Comment by BJY666** [comment]
处理器:Intel(R) Pentium(R) CPU  N3520  @ 2.16GHz   2.16 GHz
机带RAM:4.00 GB (3.89 GB 可用)
系统类型:64 位操作系统, 基于 x64 的处理器
版本:Windows Server 2022 Standard
版本号:21H2
 
这样可以吗

**Comment by RealHeart** [comment]
> 处理器:Intel(R) Pentium(R) CPU N3520 @ 2.16GHz 2.16 GHz 机带RAM:4.00 GB (3.89 GB 可用) 系统类型:64 位操作系统, 基于 x64 的处理器 版本:Windows Server 2022 Standard 版本号:21H2
> 
> 这样可以吗

使用的yunzai版本？

**Comment by BJY666** [comment]
yunzai版本是3.0.0，喵喵是2.3.8

**Comment by RealHeart** [comment]
更新最新提交后尝试使用，另外建议切换至 `Miao-Yunzai` 使用

**Comment by BJY666** [comment]
好的，谢谢大佬
