### ISSUE TITLE
feat: 希望功能支持TRSS-Yunzai到各个平台的使用

### ISSUE THREAD

**Issue by xiaoACE6716** [armoe-project/armoe-plugin#9]
因为最近QQ群机器人被杀的太厉害了，所以试图使用TRSS-Yunzai让机器人支持KOOK频道、QQ频道，以免QQ又被封了用不了，但是经过测试发现指令虽然可以在其他平台触发，但是最终的消息没法发送出来，希望作者可以支持其他平台的使用

**Comment by RealHeart** [comment]
这个你得找 TRSS-Yunzai 适配转发消息。

**Comment by xiaoACE6716** [comment]
> 这个你得找 TRSS-Yunzai 适配转发消息。

见https://github.com/TimeRainStarSky/Yunzai-KOOK-Plugin/issues/1#issuecomment-1641981254
